# Generated by Django 2.2 on 2021-01-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
