# Generated by Django 2.2 on 2021-01-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0002_auto_20210123_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deity',
            name='image',
        ),
    ]
