# Generated by Django 2.2 on 2021-01-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0003_remove_deity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deity',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deity',
            name='religion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
