# Generated by Django 2.2 on 2021-02-01 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0004_auto_20210124_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deity',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deity', to='wiki_app.User'),
        ),
    ]
